CLOUD_LINKEDIN_TOKEN = "AQVRSeKjU8njn_XWZ93Jad8mBf31qpiZyWc996DR17eGk-cfKV084Qs3OpdulIXGKPweU4M6YeeoIrg7SzXhNqcETaoqkyF763mUxXwd9zosH17FpVA_zNbGBzliCpCIH_VEHA9botL4rm9hmEAx02KznliNlNcHHFIzMU5Uap3lmpyd9yzy9VaB2myVlVAA_Nx65UOamJPbLnd_674uTBl86W2b1mFildud53r2RDwR8kvCGlDb-OWPAoN5KQGkSseCzRzXp4pLHrfJSES3K7WubHBedS2rsyZU-AkLPMN3zXu-28ChwTjYswRZSALZLV4d9yGfk6VRc_-cfHTh77qVNzakdg"

INTERNET_LINKEDIN_TOKEN = ""

CLOUD_FACEBOOK_TOKEN = ""
INTERNET_FACEBOOK_TOKEN = ""

OPENAI_KEY = "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"